on: [push]
  
name: update-website

jobs:
  update-website:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", 'bookdown','DBI','RMySQL','data.table','knitr','rmarkdown','DT'))
        shell: Rscript {0}
      - name: refresh book
        run: Rscript -e "bookdown::render_book('DatabaseQuickStart/index.Rmd', 'bookdown::gitbook')"